<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.connsec.spring.RealAuthenticationFailureHandlerTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2019-03-05T13:23:48" hostname="WIN7U-20160730R" time="0.059">
  <properties/>
  <testcase name="testOnAuthnFailureServiceProviderException" classname="com.connsec.spring.RealAuthenticationFailureHandlerTest" time="0.048"/>
  <testcase name="testOnAuthnFailureIdentityProviderException" classname="com.connsec.spring.RealAuthenticationFailureHandlerTest" time="0.008"/>
  <system-out><![CDATA[[com.connsec.spring.RealAuthenticationFailureHandler:DEBUG {} 70] saved Request: savedRequest
[com.connsec.spring.RealAuthenticationFailureHandler:WARN {} 80] Unrecoverable authn failure. Sending to Forbidden
[com.connsec.spring.RealAuthenticationFailureHandler:DEBUG {} 70] saved Request: savedRequest
[com.connsec.spring.RealAuthenticationFailureHandler:WARN {} 74] Authn Failure reported by the IDP.
[com.connsec.spring.RealAuthenticationFailureHandler:DEBUG {} 75] Retry original request of http://sp/protected
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
